### ISSUE TITLE
MP Dragons XP isn't reading properly

### ISSUE THREAD

**Issue by zably** [Neraud/PADListener#87]
When importing the MP Dragons, their XP is maxing out at 9,999,000 instead of 9,999,999 (the .json file does appear to properly show 9,999,999, it just doesn't import that way for some reason).  I emailed you my capture data as you suggested in the reddit message.

(As an aside, I was getting a "permission denied for the attachement" when trying to share the data from the share icon on the "View captured data" screen.  I did a single google search, and it was basically the same as described here:

http://stackoverflow.com/questions/26883259/gmail-5-0-app-fails-with-permission-denied-for-the-attachment-when-it-receives

but it might just be an issue on my end with my security settings.)

**Comment by OhNoBananas** [comment]
I just want to add in that I too am seeing this issue. Each time I try to do a sync it says there are monsters it doesn't recognize...and none of my new machines have been added.

**Comment by zably** [comment]
Yeah, someone already made an issue about it ( #86 ) so I didn't mention it here since I think this is a separate issue.

**Comment by Neraud** [comment]
Thanks for the capture.

PAD allows you to "over-feed" a monster. I had to cap the exp to the max allowed on each monster so that they don't appear as updated each time you sync.

For MP Dragons, PADherder is reporting an incorrect max exp (9999000). So my capped exp is also incorrect.
I've opened an issue on  [PADherder's GitHub](https://github.com/madcowfred/padherder-issues/issues/770)

**Comment by Neraud** [comment]
BTW, I've created a dedicated issue for the Gmail sharing problem : #88
